---
extends: default

locale: en_US.UTF-8

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  document-start:
    level: error
  document-end:
    level: error
  empty-values:
    level: error
  indentation:
    spaces: 2
    check-multi-line-strings: false
  line-length:
    max: 120
  octal-values: enable
  truthy:
    check-keys: false
...
